// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.3
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\ace+dds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "sonarProtoC.h"
#include "tao/CDR.h"
#include "tao/ORB_Core.h"

#if !defined (__ACE_INLINE__)
#include "sonarProtoC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\ace+dds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_cs.cpp:105

#if !defined (_OCTETSEQ_CS_)
#define _OCTETSEQ_CS_

OctetSeq::OctetSeq (void)
{}

OctetSeq::OctetSeq (
    ::CORBA::ULong max)
  : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (max)
{}

OctetSeq::OctetSeq (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    ::CORBA::Octet * buffer,
    ::CORBA::Boolean release)
  : ::TAO::unbounded_value_sequence< ::CORBA::Octet>
    (max, length, buffer, release)
{}

OctetSeq::OctetSeq (
    const OctetSeq &seq)
  : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (seq)
{}

OctetSeq::~OctetSeq (void)
{}

#endif /* end #if !defined */

// TAO_IDL - Generated from
// d:\ace+dds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\cdr_op_cs.cpp:93
#if !defined _TAO_CDR_OP_OctetSeq_CPP_
#define _TAO_CDR_OP_OctetSeq_CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OctetSeq &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OctetSeq &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_OctetSeq_CPP_ */

// TAO_IDL - Generated from
// d:\ace+dds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:49

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const org::omg::dds::SonarSimu::SonarProtocol &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.OctetSeqLength) &&
    (strm << _tao_aggregate.data);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    org::omg::dds::SonarSimu::SonarProtocol &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.OctetSeqLength) &&
    (strm >> _tao_aggregate.data);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\ace+dds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:49

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const org::omg::dds::SonarSimu::SonarProtocolII &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.speed) &&
    (strm << _tao_aggregate.screwNu) &&
    (strm << _tao_aggregate.screwVelocity) &&
    (strm << _tao_aggregate.activeDetectMode) &&
    (strm << _tao_aggregate.traceMode) &&
    (strm << _tao_aggregate.sweepBandNum) &&
    (strm << _tao_aggregate.eclipse) &&
    (strm << _tao_aggregate.sonarX) &&
    (strm << _tao_aggregate.sonarY) &&
    (strm << _tao_aggregate.sonarDepth) &&
    (strm << _tao_aggregate.sonarX2) &&
    (strm << _tao_aggregate.sonarY2) &&
    (strm << _tao_aggregate.sonarDepth2) &&
    (strm << _tao_aggregate.explosionInterval) &&
    (strm << _tao_aggregate.amorVolume);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    org::omg::dds::SonarSimu::SonarProtocolII &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.speed) &&
    (strm >> _tao_aggregate.screwNu) &&
    (strm >> _tao_aggregate.screwVelocity) &&
    (strm >> _tao_aggregate.activeDetectMode) &&
    (strm >> _tao_aggregate.traceMode) &&
    (strm >> _tao_aggregate.sweepBandNum) &&
    (strm >> _tao_aggregate.eclipse) &&
    (strm >> _tao_aggregate.sonarX) &&
    (strm >> _tao_aggregate.sonarY) &&
    (strm >> _tao_aggregate.sonarDepth) &&
    (strm >> _tao_aggregate.sonarX2) &&
    (strm >> _tao_aggregate.sonarY2) &&
    (strm >> _tao_aggregate.sonarDepth2) &&
    (strm >> _tao_aggregate.explosionInterval) &&
    (strm >> _tao_aggregate.amorVolume);
}

TAO_END_VERSIONED_NAMESPACE_DECL



