// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.3
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\ace+dds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "sonarProtoTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "sonarProtoTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\ace+dds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for org::omg::dds::SonarSimu::SonarProtocolTypeSupport.

org::omg::dds::SonarSimu::SonarProtocolTypeSupport_ptr
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolTypeSupport>::duplicate (
    org::omg::dds::SonarSimu::SonarProtocolTypeSupport_ptr p)
{
  return org::omg::dds::SonarSimu::SonarProtocolTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolTypeSupport>::release (
    org::omg::dds::SonarSimu::SonarProtocolTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

org::omg::dds::SonarSimu::SonarProtocolTypeSupport_ptr
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolTypeSupport>::nil (void)
{
  return org::omg::dds::SonarSimu::SonarProtocolTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolTypeSupport>::marshal (
    const org::omg::dds::SonarSimu::SonarProtocolTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



org::omg::dds::SonarSimu::SonarProtocolTypeSupport::SonarProtocolTypeSupport (void)
{}

org::omg::dds::SonarSimu::SonarProtocolTypeSupport::~SonarProtocolTypeSupport (void)
{
}

org::omg::dds::SonarSimu::SonarProtocolTypeSupport_ptr
org::omg::dds::SonarSimu::SonarProtocolTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SonarProtocolTypeSupport::_duplicate (
      dynamic_cast<SonarProtocolTypeSupport_ptr> (_tao_objref));
}

org::omg::dds::SonarSimu::SonarProtocolTypeSupport_ptr
org::omg::dds::SonarSimu::SonarProtocolTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SonarProtocolTypeSupport::_duplicate (
      dynamic_cast<SonarProtocolTypeSupport_ptr> (_tao_objref));
}

org::omg::dds::SonarSimu::SonarProtocolTypeSupport_ptr
org::omg::dds::SonarSimu::SonarProtocolTypeSupport::_nil (void)
{
  return 0;
}

org::omg::dds::SonarSimu::SonarProtocolTypeSupport_ptr
org::omg::dds::SonarSimu::SonarProtocolTypeSupport::_duplicate (SonarProtocolTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
org::omg::dds::SonarSimu::SonarProtocolTypeSupport::_tao_release (SonarProtocolTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
org::omg::dds::SonarSimu::SonarProtocolTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:org/omg/dds/SonarSimu/SonarProtocolTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* org::omg::dds::SonarSimu::SonarProtocolTypeSupport::_interface_repository_id (void) const
{
  return "IDL:org/omg/dds/SonarSimu/SonarProtocolTypeSupport:1.0";
}

::CORBA::Boolean
org::omg::dds::SonarSimu::SonarProtocolTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\ace+dds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for org::omg::dds::SonarSimu::SonarProtocolDataWriter.

org::omg::dds::SonarSimu::SonarProtocolDataWriter_ptr
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolDataWriter>::duplicate (
    org::omg::dds::SonarSimu::SonarProtocolDataWriter_ptr p)
{
  return org::omg::dds::SonarSimu::SonarProtocolDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolDataWriter>::release (
    org::omg::dds::SonarSimu::SonarProtocolDataWriter_ptr p)
{
  ::CORBA::release (p);
}

org::omg::dds::SonarSimu::SonarProtocolDataWriter_ptr
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolDataWriter>::nil (void)
{
  return org::omg::dds::SonarSimu::SonarProtocolDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolDataWriter>::marshal (
    const org::omg::dds::SonarSimu::SonarProtocolDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



org::omg::dds::SonarSimu::SonarProtocolDataWriter::SonarProtocolDataWriter (void)
{}

org::omg::dds::SonarSimu::SonarProtocolDataWriter::~SonarProtocolDataWriter (void)
{
}

org::omg::dds::SonarSimu::SonarProtocolDataWriter_ptr
org::omg::dds::SonarSimu::SonarProtocolDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SonarProtocolDataWriter::_duplicate (
      dynamic_cast<SonarProtocolDataWriter_ptr> (_tao_objref));
}

org::omg::dds::SonarSimu::SonarProtocolDataWriter_ptr
org::omg::dds::SonarSimu::SonarProtocolDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SonarProtocolDataWriter::_duplicate (
      dynamic_cast<SonarProtocolDataWriter_ptr> (_tao_objref));
}

org::omg::dds::SonarSimu::SonarProtocolDataWriter_ptr
org::omg::dds::SonarSimu::SonarProtocolDataWriter::_nil (void)
{
  return 0;
}

org::omg::dds::SonarSimu::SonarProtocolDataWriter_ptr
org::omg::dds::SonarSimu::SonarProtocolDataWriter::_duplicate (SonarProtocolDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
org::omg::dds::SonarSimu::SonarProtocolDataWriter::_tao_release (SonarProtocolDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
org::omg::dds::SonarSimu::SonarProtocolDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:org/omg/dds/SonarSimu/SonarProtocolDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* org::omg::dds::SonarSimu::SonarProtocolDataWriter::_interface_repository_id (void) const
{
  return "IDL:org/omg/dds/SonarSimu/SonarProtocolDataWriter:1.0";
}

::CORBA::Boolean
org::omg::dds::SonarSimu::SonarProtocolDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\ace+dds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for org::omg::dds::SonarSimu::SonarProtocolDataReader.

org::omg::dds::SonarSimu::SonarProtocolDataReader_ptr
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolDataReader>::duplicate (
    org::omg::dds::SonarSimu::SonarProtocolDataReader_ptr p)
{
  return org::omg::dds::SonarSimu::SonarProtocolDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolDataReader>::release (
    org::omg::dds::SonarSimu::SonarProtocolDataReader_ptr p)
{
  ::CORBA::release (p);
}

org::omg::dds::SonarSimu::SonarProtocolDataReader_ptr
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolDataReader>::nil (void)
{
  return org::omg::dds::SonarSimu::SonarProtocolDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<org::omg::dds::SonarSimu::SonarProtocolDataReader>::marshal (
    const org::omg::dds::SonarSimu::SonarProtocolDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



org::omg::dds::SonarSimu::SonarProtocolDataReader::SonarProtocolDataReader (void)
{}

org::omg::dds::SonarSimu::SonarProtocolDataReader::~SonarProtocolDataReader (void)
{
}

org::omg::dds::SonarSimu::SonarProtocolDataReader_ptr
org::omg::dds::SonarSimu::SonarProtocolDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SonarProtocolDataReader::_duplicate (
      dynamic_cast<SonarProtocolDataReader_ptr> (_tao_objref));
}

org::omg::dds::SonarSimu::SonarProtocolDataReader_ptr
org::omg::dds::SonarSimu::SonarProtocolDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SonarProtocolDataReader::_duplicate (
      dynamic_cast<SonarProtocolDataReader_ptr> (_tao_objref));
}

org::omg::dds::SonarSimu::SonarProtocolDataReader_ptr
org::omg::dds::SonarSimu::SonarProtocolDataReader::_nil (void)
{
  return 0;
}

org::omg::dds::SonarSimu::SonarProtocolDataReader_ptr
org::omg::dds::SonarSimu::SonarProtocolDataReader::_duplicate (SonarProtocolDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
org::omg::dds::SonarSimu::SonarProtocolDataReader::_tao_release (SonarProtocolDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
org::omg::dds::SonarSimu::SonarProtocolDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:org/omg/dds/SonarSimu/SonarProtocolDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* org::omg::dds::SonarSimu::SonarProtocolDataReader::_interface_repository_id (void) const
{
  return "IDL:org/omg/dds/SonarSimu/SonarProtocolDataReader:1.0";
}

::CORBA::Boolean
org::omg::dds::SonarSimu::SonarProtocolDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

